[package]
name = "logjam"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.5"
toml = "0.8.13"
serde = { version = "1.0.202", features = ["serde_derive"] }
