name = "TestMap"
hi_score = 0
width = 600
height = 600
tiles = [
    [
        "Log",
        "Water",
        "Water",
        "Water",
        "Water",
        "Water",
        "Water",
        "Water",
    ],
    [
        "Log",
        "Water",
        "Log",
        "Log",
        "Water",
        "Water",
        "Water",
        "Water",
    ],
    [
        "Log",
        "Log",
        "Water",
        "Log",
        "Water",
        "Water",
        "Water",
        "Water",
    ],
    [
        "Water",
        "Water",
        "Water",
        "Water",
        "Water",
        "Water",
        "Water",
        "Water",
    ],
    [
        "Log",
        "Water",
        "Log",
        "Log",
        "Water",
        "Water",
        "Water",
        "Water",
    ],
    [
        "Log",
        "Log",
        "Water",
        "Log",
        "Water",
        "Water",
        "Water",
        "Water",
    ],
    [
        "Water",
        "Water",
        "Water",
        "Exit",
        "Water",
        "Water",
        "Water",
        "Water",
    ],
    [
        "Water",
        "Water",
        "Water",
        "Water",
        "Water",
        "Water",
        "Water",
        "Water",
    ],
]
