name: Zig Build Linux

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - run: sudo apt-get update
      - run: sudo apt-get install --fix-missing -no-install-recommends libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libglew-dev libopenal-dev  libgl1-mesa-dev
      - run: zig build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig fmt --check src/*.zig
